{{- if eq .Values.workload.kind "statefulset" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-info-chart.fullname" . }}-headless
  labels:
    {{- include "devops-info-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devops-info-chart.selectorLabels" . | nindent 4 }}
{{- end }}
