replicaCount: 3

image:
  repository: pakmengamer/devops-info-service
  pullPolicy: IfNotPresent
  tag: "1.0.1"

nameOverride: ""
fullnameOverride: ""
workload:
  kind: rollout
serviceAccount:
  create: true
  name: ""

podAnnotations:
  rollout-demo: "v1"
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080
config:
  fileName: config.json
  mountPath: /config
envConfig:
  APP_ENV: "dev"
  LOG_LEVEL: "INFO"
  FEATURE_VISITS_COUNTER: "true"
persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
  mountPath: /data

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

env:
  - name: PORT
    value: "5000"
  - name: VISITS_FILE
    value: "/data/visits"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
rollout:
  strategy: canary
  blueGreen:
    autoPromotionEnabled: false

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

hooks:
  image: busybox:1.36
  preInstall:
    enabled: true
    weight: -5
  postInstall:
    enabled: true
    weight: 5
secret:
  enabled: true
  name: ""
  data:
    username: "change-me"
    password: "change-me"
vault:
  enabled: false
  role: "devops-info-role"
  secretPath: "secret/data/myapp/config"
  fileName: "config"
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
