replicaCount: 5

image:
  tag: "1.0.1"
envConfig:
  APP_ENV: "prod"
  LOG_LEVEL: "INFO"
  FEATURE_VISITS_COUNTER: "true"
persistence:
  enabled: true
  size: 200Mi
  storageClass: ""
  mountPath: /data

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
  nodePort: null

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 3
